# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-02 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.ImageField(blank=True, default='media/default.jpeg', upload_to='users/%Y/%m/%d'),
        ),
    ]
