# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-02 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180402_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.FileField(upload_to=''),
        ),
    ]
