# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-02 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180402_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Actor',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
