# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[movies.models.validate_movie_rating])),
                ('time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Rater')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('rater', 'movie')]),
        ),
    ]
