# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20180406_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Actor',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
