# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20180410_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Actor',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
