# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20180411_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='time_added',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
