# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20180411_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating_Count',
            field=models.FloatField(default=0.0),
        ),
    ]
