# Generated by Django 2.0.4 on 2018-04-13 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20180412_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='user',
            field=models.OneToOneField(null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete='cascade', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete='cascade', to='movies.Rater'),
        ),
    ]
