# Generated by Django 2.0.4 on 2018-04-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20180413_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rater',
            name='gender',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='rater',
            name='job',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rater',
            name='zip_code',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
